[build]
    command="npm install && npm run build && npm run build:lambda"
    # functions="lambda"
    functions="build/lambda"
    publish="build"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/notion-form"
