[build]
    command="npm install && npm run build && npm run build:lambda"
    functions="lambda/"
    publish="build"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/notion-form"
    status = 200
    force = true
    # headers = {X-From = "Netlify"}

[[redirects]]
    from = "/update"
    to = "/.netlify/functions/notion-form-update"
    status = 200
    force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
      
