[build]
    command="npm install && npm run build && npm run build:lambda"
    functions="lambda"
    publish="build"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/notion-form"
    status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
      
